version: 2

jobs:
  build:
    docker:
      - image: node:6.8.1

    steps:
      - checkout
      - run:
        - curl -s https://raw.githubusercontent.com/chronogolf/circleci-google-chrome/master/use_chrome_stable_version.sh | bash
        - npm install
        - ./node_modules/gulp/bin/gulp.js clean
        - ./node_modules/gulp/bin/gulp.js build
        - ./node_modules/gulp/bin/gulp.js publish
  test:

workflows:
  version: 2
  wname:
    - build
    # - test  

    # # Add some environment variables
    #   environment:

    # ## Customize dependencies
    # dependencies:
    #   pre:
    #     - curl -s https://raw.githubusercontent.com/chronogolf/circleci-google-chrome/master/use_chrome_stable_version.sh | bash

    #   override:
    #     - npm install

    #   post:
    #     - ./node_modules/gulp/bin/gulp.js clean
    #     - ./node_modules/gulp/bin/gulp.js build
    #     - ./node_modules/gulp/bin/gulp.js publish

    # compile:
    #   override:
    # ##    - npm run build

    # test:
    #   override:
    #     - npm run test

    # deployment:
    #   prod:
    #     branch: master
    #     commands:
    #       - ./deploy.sh PROD admin.topcoder.com
    #   dev:
    #     branch: dev
    #     commands:
    #       - ./deploy.sh DEV admin.topcoder-dev.com
